global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vs_opc_gateway'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          job: vs_opc

remote_write:
  - url: "http://victoria-metrics:8428/api/v1/write"
